# Generated by Django 5.2.7 on 2025-10-01 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Author',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('genre', models.CharField(choices=[('badiiy', 'Badiiy'), ('fantastik', 'Fantastik'), ('ilmiy', 'Ilmiy'), ('romantik', 'Romantik'), ('diniy', 'Diniy')], max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Book',
                'ordering': ['created_at'],
            },
        ),
    ]
